[package]
workspace = ".."
name = "m3-pc"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tetra = "0.8.0"
vek = { version = "0.15.10", default-features = false }

#[target.'cfg(windows)'.build-dependencies]
[build-dependencies]
attohttpc = { version = "0.25.0", default-features = false, features = ["tls-rustls-webpki-roots"] }
piz = "0.5.1"
