[package]
workspace = ".."
name = "m3-pybadge"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
pybadge-high = { git = "https://github.com/LuckyTurtleDev/pybadge-high.git", branch = "main", default-features = false }
