name: Rust

on:
  push:
  pull_request:
  release:
    types: [released]


jobs:
  check_pybadge:
    runs-on: ubuntu-latest
    name: "check pybadge"
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        id: "rust-toolchain"
        with:
          targets: thumbv7em-none-eabihf
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: "Pybadge ${{runner.os}} Rust ${{steps.rust-toolchain.outputs.cachekey}} Lock ${{hashFiles('Cargo.lock')}}"
      - run: cargo check --all-features --target thumbv7em-none-eabihf
        env:
          RUST_BACKTRACE: 1
      - run: cargo check --all-features
        env:
          RUST_BACKTRACE: 1


  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check
